### ISSUE TITLE
weather.sh regex error

### ISSUE THREAD

**Issue by zimbipw** [luispabon/sway-dotfiles#1]
this line
 temperature=$(echo ${weather[2]} | sed -E 's/([[:digit:]])+\.\./\1 to /g')
should read
temperature=$(echo ${weather[2]} | sed -E 's/([[:digit:]]+)\.\./\1 to /g')
(the + is in the bracket), otherwise the script makes out of something like 27..32 7 to 32

**Comment by luispabon** [comment]
Apologies, it looks like I had turned off notifications for this repo and never saw this issue.

Closed via 79722f6f8b8f3d9f0a98150e864edde8555debae
